import SideBar from "@/components/SideBar";
import "@/styles/globals.css";
import { SessionProvider } from "@/components/SessionProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import Navbar from "@/components/Navbar";
import Login from "@/components/Login";
import Colors from "@/assets/theme/colors";

export const metadata = {
  title: "VogueGenie",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <head />
      <body>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ) : (
            <div className="flex flex-col h-screen">
              <div className="flex">
                <Navbar />
              </div>
              <div
                className=" mt-16 flex h-full"
                style={{ backgroundColor: Colors.bgwhite }}
              >
                <div className="max-w-xs h-full md:min-w-[20rem] py-3 px-2">
                  <SideBar />
                </div>
              </div>

              {/* <div className="flex h-full bg-red-500" >
                <div className="max-w-xs h-full md:min-w-[20rem] bg-green-500">
                  <SideBar />
                </div>
                <div className="flex-1">{children}</div>
              </div> */}
            </div>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}
